language: php

sudo: false

cache:
    directories:
        - $HOME/.composer

php:
    - 7.2
    - 7.3
    - 7.4
env:
    - deps=^3.4
    - deps=^4.4
    - deps=^5.0

install:
    - sed -i.bak "s/\^3.4 || ^4.4 || ^5.0/${deps}/" composer.json
    - composer --prefer-dist -n --no-progress update

script:
    - vendor/bin/php-cs-fixer fix  --config=.php_cs.dist --dry-run
    - composer test
