language: php

sudo: false

cache:
    directories:
        - $HOME/.composer

php:
    - 7.2
    - 7.3
    - 7.4
env:
    - deps=high
    - deps=low

install:
    - if [ "$deps" = "high" ]; then composer --prefer-dist -n --no-progress update; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-dist -n --no-progress --prefer-lowest update; fi;

script:
    - composer test
